### PR TITLE
Fix for new file scheme.

### PR DESCRIPTION
**Pull request by bpinaya**
Hi there, love your script, better than having those pesky TensorFlow Record files, I had trouble using it as mentioned in issue #3 , I fiddled around a bit and saw  that this small index was off, now that the current file scheme looks like this:
filescheme
With that the script runs properly, if I can I'll see what I can improve from my side. Good job so far!

### CODE REVIEW

**Comment by gsssrao** [comment]
Hi @bpinaya thanks for pointing this out and for the pull request. 

But, I think that the problem is rather with awk and its versioning. Could you tell which os you are using and the output of the following commands:
```
man awk | head -n 1
```

In case the first one says `gawk`, could you tell me the output of the following:
```
gawk --version | head -n 1  
```

My guess is that probably you have something like gawk 3.x on your system. Usually, linux systems ship with `gawk` or `mawk` whereas osx ships with `nawk` (true awk). Now, these different awks have some minor differences and my script usually works similar across all of them but it turns out that the `substr` function in `awk` behaves differently on some types and versions of awk. Even across same type of awk like say `gawk`, `gawk` 3.x and 4.0 have differences. 

I tested the current version of repo with `substr($0,0,2)` and it works well on osx and linux distros running `gawk` 4.x. 

I think that a simpler solution to avoiding this problem altogether would be to use `cut` and simple bash read line with `echo`.

**Comment by gsssrao** [comment]
I think that f1261f8d9f098cb2f44db5721cd3f8e14bbda097 should fix the issue across all the os versions. Could you please check and let me know if the current version of the repository works on your system?

**Comment by bpinaya** [comment]
The output for:
```
gawk --version | head -n 1  
```
is
```
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
```
I think you solved it in [#f1261f8](https://github.com/gsssrao/youtube-8m-videos-frames/commit/f1261f8d9f098cb2f44db5721cd3f8e14bbda097), I'll test later.
I was using Xubuntu 16.06 with kerner `4.13.0-43-generic`

**Comment by bpinaya** [comment]
I saw you addressed the thingy in the `mv`, also the previos problem is fixing, closing this PR.

**Pull request closed without merging**
